<html xmlns:concordion="http://www.concordion.org/2007/concordion">
<head>
    <link href="../../../../concordion.css" rel="stylesheet" type="text/css" />
    <title>"Fail-fast" option</title>
</head>
<body>

    <h1>"Fail-fast" option</h1>

    <p>
        By default, exceptions are reported but Concordion continues
        processing the rest of the test. (<a href="ContinueAfterExceptions.html">More details</a>)
    </p>

    <p> However, fixtures can be annotated with <code>@FailFast</code> to stop further
        processing if an exception is encountered. This can be useful if further processing
        after an exception is undesirable (e.g. because it's slow, could cause corruption or
        would make the results hard to explain to others). It is possible to
        <a href="FailFastOnSpecificExceptions.html" concordion:run="concordion">specify specific exceptions</a> on the <code>@FailFast</code>
        annotation.
    </p>

    <p>
        Note that the @FailFast annotation is <a href="FailFastPassthrough.html" concordion:run="concordion">transitive</a> when used with the <a href="../run/Run.html" concordion:run="concordion">run command</a>. That is:
        <ul>
            <li>Given one fixture executes another fixture, and both fixtures are annotated with @FailFast,</li>
            <li>When the called test throws an exception, </li>
            <li>Then further processing of both tests is stopped. </li>
        </ul>
    </p>

    <div class="example">

        <h3>Example</h3>

        <p>When the fixture is annotated with <code>@FailFast</code> and processes the following:</p>

<pre class="html" concordion:set="#fragment">
&lt;p concordion:execute="myExceptionThrower()"&gt;
This method throws an exception.
&lt;/p&gt;

&lt;p concordion:execute="myMethod()"&gt;
This method executes quietly.
&lt;/p&gt;
</pre>

        <p>
            It <span concordion:assertEquals="myMethodWasCalledProcessing(#fragment) ? 'calls' : 'does not call'">does not call</span>
            <code>myMethod()</code> in the Java fixture code because the exception thrown by the
            first method call stops further processing of the test.
        </p>

    </div>


</body>
</html>